import Head from 'next/head'
import Image from 'next/image'
import Advertisement from '../components/Advertisement'
import Footer from '../components/Footer'
import Market from '../components/Market'
import MiddleBanner from '../components/MiddleBanner'
import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div className='home'>
      <Head>
        <title>crypto currency | landing page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='w-full min-h-screen bg-blueish'>
        <Navbar />
        <MiddleBanner />
        <Advertisement />
        <Market />
        <Footer />
        
      </main>

     
    </div>
  )
}
